services:
  # Banco de Dados PostgreSQL
  db:
    image: postgis/postgis:18-3.6
    container_name: sabor-na-nuvem-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Node.js
  api:
    container_name: sabor-na-nuvem-api
    build:
      context: .
      secrets:
        - npmrc
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:

secrets:
  npmrc:
    file: .npmrc
