services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: sabor-na-nuvem-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # API Node.js
  api:
    container_name: sabor-na-nuvem-api
    build: .
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - db

volumes:
  pgdata:
